Homework # 1 complete
zhuchkov-artem/homework-repository pull request #1
Opened 2021-11-09 19:48 UTC by zhuchkov-artem

2021-11-10 07:26 UTC, PeppaTheC requested changes

2021-11-10 07:26 UTC, PeppaTheC commented on homework1/task02.py
> +def _check_window(x: int, y: int, z: int) -> bool:
что значит это название check_window?

2021-11-10 07:26 UTC, PeppaTheC commented on homework1/task02.py
> +    assert len(data) >= 3
почему тут assert? важно помнить, что при включении оптимизации кода python все assert в коде игнорируются

2021-11-10 07:26 UTC, PeppaTheC commented on homework1/task02.py
> +        data = data[1:]
выглядит не очень оптимально по памяти, перекопировать каждый раз список (-1 элемент). Какая тут сложность по памяти?

2021-11-10 07:26 UTC, PeppaTheC commented on homework1/task03.py
> +    max_value = - float('inf')
при пустом файле, мы получим + бесконечность? ожидаемое ли это поведение?

2021-11-10 07:26 UTC, PeppaTheC commented on homework1/task03.py
> +            numbers = list(map(int, line.split()))
я бы еще strip() добавил, чтобы убрать лишние отступы

2021-11-10 07:26 UTC, PeppaTheC commented on homework1/task03.py
> +    with open(file_name) as file:
лучше явно указывать, как мы открываем файл (на чтение, на запись)

2021-11-10 07:26 UTC, PeppaTheC commented on homework1/task04.py
> +                        result += 1
какая временная сложность при решении таким алгоритмом?

2021-11-10 07:26 UTC, PeppaTheC commented on homework1/task05.py
> +    assert len(nums) > 0, k > 0
опять assert. assert стоит использовать только для отладки и дебага кода. Он не должен влиять на бизнес логику приложения.
https://stackoverflow.com/questions/1273211/disable-assertions-in-python

2021-11-10 07:26 UTC, PeppaTheC commented on homework1/task05.py
> +    answer = - float('inf')
опять же при k=0 мы получим обратно float, хотя по аннотации типов ожидаем int.

2021-11-10 07:26 UTC, PeppaTheC commented on homework1/task05.py
> +            sums_of_subarrays.append(sum(nums[i:i + subarray_size]))
тут много лишних итераций? зачем мы проходим по полной длиннее массива? начиная с определенного элемента мы будем получать, всегда один и тот же список.

2021-11-10 07:26 UTC, PeppaTheC commented on homework1/task05.py
> +    answer = - float('inf')
float('-inf') - более ожидаемо, чем инвертировать бесконечность

2021-11-10 07:26 UTC, PeppaTheC commented on tests/homework1/test_task02.py
> +    assert check_fibonacci([0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233,
тест должны легко читаться, и проверять граничные условия, и можно 1-2 на бизнес логику.

2021-11-10 07:26 UTC, PeppaTheC commented on tests/homework1/test_task02.py
> +    assert not check_fibonacci([0, 1, 1, 2, 6])
надо разделить на два разных теста, а не проверять в одном два разных условия

2021-11-10 07:26 UTC, PeppaTheC commented on tests/homework1/test_task03.py
> +        print('1 20 3 44 -5', '12 0 100 1', sep='\n', file=file)
это, что-то странное, почему тут не просто запись в файл, а перенаправления stdout в файл?

2021-11-10 07:26 UTC, PeppaTheC commented on tests/homework1/test_task03.py
> +    with open('testing_file.txt', mode='w') as file:
опять надо разделить на два теста

2021-11-10 07:26 UTC, PeppaTheC commented on tests/homework1/test_task04.py
> +    assert check_sum_of_four(a, b, c, d) == 16
тоже самое - это разные тест кейсы

2021-11-10 07:26 UTC, PeppaTheC commented on tests/homework1/test_task05.py
> +    assert find_maximal_subarray_sum(nums=[1, 3, -1, -3, 5, 3, 6, 7],
разделить

2021-11-10 08:53 UTC, zhuchkov-artem commented on homework1/task02.py
> +def _check_window(x: int, y: int, z: int) -> bool:
Как я понял из докстринга, в этом задании надо было переделать неверно работающий код из Юпитер Ноутбука лекции № 1. Соответственно, это функция и ее название взяты оттуда. Она "проверяет окно", которое ей передали на соответствие свойству чисел Фибонначи.

2021-11-10 09:03 UTC, zhuchkov-artem commented on homework1/task02.py
> +    assert len(data) >= 3
Каким способом тогда лучше проверять, что полученные данные корректны?

2021-11-10 09:07 UTC, zhuchkov-artem commented on homework1/task02.py
> +        data = data[1:]
Это было взято также из Юпитер Ноутбука лекции. В данном случае функция использует O(n) дополнительной памяти.

2021-11-10 09:25 UTC, zhuchkov-artem commented on homework1/task03.py
> +    max_value = - float('inf')
В задании указано, что гарантируется существование файла и наличие в нем чисел

2021-11-10 09:30 UTC, zhuchkov-artem commented on homework1/task03.py
> +            numbers = list(map(int, line.split()))
В данном же случае, если в split() не передавать разделитель, то он разобьет по пробельным символам, а отступы тоже являются пробельными символами и разбиение будет корректным.

2021-11-10 09:39 UTC, zhuchkov-artem commented on homework1/task03.py
> +    with open(file_name) as file:
Исправлено

2021-11-10 09:41 UTC, zhuchkov-artem commented on homework1/task04.py
> +                        result += 1
O(n**4). Сделать быстрее и не получится, нам же надо пройти все возможные варианты

2021-11-10 09:42 UTC, zhuchkov-artem commented on homework1/task05.py
> +    assert len(nums) > 0, k > 0
В данном случае assert'ом проверяю, что введенные данные корректны. Каким тогда способом проверки лучше воспользоваться или не проверять вовсе?

2021-11-10 09:44 UTC, zhuchkov-artem commented on homework1/task05.py
> +    answer = - float('inf')
По смыслу задания k должен быть целым числом и быть больше 0. Опять возникает вопрос корректности введенных данных

2021-11-10 09:46 UTC, zhuchkov-artem commented on homework1/task05.py
> +    answer = - float('inf')
Исправлено

2021-11-10 09:57 UTC, zhuchkov-artem commented on homework1/task05.py
> +            sums_of_subarrays.append(sum(nums[i:i + subarray_size]))
Исправлено

2021-11-10 10:30 UTC, zhuchkov-artem commented on tests/homework1/test_task02.py
> +    assert check_fibonacci([0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233,
Исправлено

2021-11-10 10:32 UTC, zhuchkov-artem commented on tests/homework1/test_task02.py
> +    assert not check_fibonacci([0, 1, 1, 2, 6])
Исправлено

2021-11-10 10:33 UTC, zhuchkov-artem commented on tests/homework1/test_task05.py
> +    assert find_maximal_subarray_sum(nums=[1, 3, -1, -3, 5, 3, 6, 7],
Исправлено

2021-11-10 10:35 UTC, zhuchkov-artem commented on tests/homework1/test_task04.py
> +    assert check_sum_of_four(a, b, c, d) == 16
Исправлено

2021-11-10 10:36 UTC, zhuchkov-artem commented on tests/homework1/test_task03.py
> +    with open('testing_file.txt', mode='w') as file:
Исправлено

2021-11-10 10:36 UTC, zhuchkov-artem commented on tests/homework1/test_task03.py
> +        print('1 20 3 44 -5', '12 0 100 1', sep='\n', file=file)
Исправлено

2021-11-12 20:12 UTC, PeppaTheC commented on homework1/task02.py
> +    assert len(data) >= 3
пока не пройдены исключения, можно не проверять. 
Но если очень хочется, можно через if.
Или если уж начали через `rasie Exception` - exception нужно подобрать соответствующий логике

2021-11-12 20:12 UTC, PeppaTheC commented on homework1/task02.py
> +def _check_window(x: int, y: int, z: int) -> bool:
название выглядит просто странным

2021-11-12 20:31 UTC, PeppaTheC requested changes

2021-11-12 20:31 UTC, PeppaTheC commented on .gitignore
> +**probe.py
что тут значит, двойная звездочка?
https://git-scm.com/docs/gitignore

2021-11-12 20:31 UTC, PeppaTheC commented on homework1/task04.py
> +                        result += 1
нет не надо, достаточно посчитать количество сумм первых двух любых массивов а затем ... (додумай решение)

```pyhthon
    quantity = 0
    sums = {}
    for i in a:
        for j in b:
            if i + j in sums:
                sums[i + j] += 1
            else:
                sums[i + j] = 1
    for i in c:
        for j in d:
```

2021-11-12 20:31 UTC, PeppaTheC commented on homework1/task05.py
> +    assert len(nums) > 0, k > 0
см выше

2021-11-12 20:31 UTC, PeppaTheC commented on tests/homework1/test_task02.py
> +def test_1_check_fibonacci():
названия тестов должны быть говорящими

2021-11-12 20:48 UTC, zhuchkov-artem commented on .gitignore
> +**probe.py
Указание на все подпапки. probe.py такой "пробный" файл или черновик, где мне удобно набрасывать решения. Добавил его в .gitignor, чтобы он не отслеживался

2021-11-12 20:49 UTC, zhuchkov-artem commented on tests/homework1/test_task02.py
> +def test_1_check_fibonacci():
Можно пример?

2021-11-13 19:26 UTC, zhuchkov-artem commented on homework1/task02.py
> +    assert len(data) >= 3
Исправлено

2021-11-13 19:31 UTC, zhuchkov-artem commented on homework1/task05.py
> +    assert len(nums) > 0, k > 0
Исправлено

2021-11-13 19:42 UTC, zhuchkov-artem commented on homework1/task04.py
> +                        result += 1
Исправлено, теперь временная сложность O(n**2)

2021-11-14 14:04 UTC, PeppaTheC requested changes

2021-11-14 14:04 UTC, PeppaTheC commented on homework1/task02.py
> +        raise IndexError('Sequence contains less than 3 elements')
почему тут  IndexError error? разве оно больше подходит по значению?

2021-11-14 14:04 UTC, PeppaTheC commented on homework1/task05.py
> +        raise IndexError('Sequence is empty')
тут тоже больше подходит ValueError

2021-11-16 07:19 UTC, zhuchkov-artem commented on .gitignore
> +**probe.py
Единичный asterick заменяет любое количество символов (ноль или больше). В данном случае все 3 варианта: **probe.py, *probe.py, probe.py будут равнозначны. То есть звездочки здесь избыточны.

2021-11-16 19:37 UTC, zhuchkov-artem commented on homework1/task02.py
> +        raise IndexError('Sequence contains less than 3 elements')
Исправлено

2021-11-16 19:37 UTC, zhuchkov-artem commented on homework1/task05.py
> +        raise IndexError('Sequence is empty')
Исправлено

2021-11-16 19:47 UTC, zhuchkov-artem commented on .gitignore
> +**probe.py
- Звёздочка (*) заменяет любое количество символов
- Две звёздочки (**) используются для указания всех подпапок.

То есть 2 звездочки используются для обозначения всех подпапок, а одна звездочка используется для обозначения любого имени файла. В конкретном данном случае 2 звездочки скорей всего избыточны и можно было бы указать просто probe.py

2021-11-16 19:48 UTC, zhuchkov-artem commented on tests/homework1/test_task02.py
> +def test_1_check_fibonacci():
Исправлено

2021-11-21 17:28 UTC, PeppaTheC approved these changes

2021-11-29 13:07 UTC, PeppaTheC approved these changes

2021-11-29 19:33 UTC, merged