Homework № 2 completed
zhuchkov-artem/homework-repository pull request #2
Opened 2021-11-13 19:15 UTC by zhuchkov-artem

2021-11-14 14:40 UTC, PeppaTheC requested changes

2021-11-14 14:40 UTC, PeppaTheC commented on homework2/hw1.py
> +    chars_stat = Counter()
автор задания, под " Complete using only default collections" подразумевал запрет на использование collections модуля

2021-11-14 14:40 UTC, PeppaTheC commented on homework2/hw1.py
> +                if char in string.punctuation:
string.punctuation - тут коллекция только ascii пунктуаций - в файле встречаются еще и non ascii символы пунктуации

2021-11-14 14:40 UTC, PeppaTheC commented on homework2/hw1.py
> +                if ord(char) > 127:
лучше заместо вычисления ord и сравнение с константой использовать внутренний метод строк.

2021-11-14 14:40 UTC, PeppaTheC commented on homework2/hw3.py
> +    return list(map(list, product(*args)))
from itertools import product
- нужно решение без product - его можно в тестах использовать для проверки.

2021-11-14 14:40 UTC, PeppaTheC commented on homework2/hw4.py
> +    def wrapper(*some):
keywords, default args - судя не попадут. 
Но это на оценку с плюсом, так к слову.

2021-11-14 14:40 UTC, PeppaTheC commented on homework2/hw5.py
> +    for i, element in enumerate(data):
https://docs.python.org/3/library/stdtypes.html#common-sequence-operations
ручной поиск для sequence лучше заменить

2021-11-14 14:40 UTC, PeppaTheC commented on homework2/hw5.py
> +        if element == stop:
что тут в seq из чисел при 
`start, stop = 0, start` 
start 0 будет?

2021-11-14 14:40 UTC, PeppaTheC commented on tests/homework2/test_hw2.py
> +def test_1_major_and_minor_elem():
naming

2021-11-29 19:46 UTC, zhuchkov-artem commented on homework2/hw3.py
> +    return list(map(list, product(*args)))
Исправлено

2021-11-29 19:46 UTC, zhuchkov-artem commented on homework2/hw4.py
> +    def wrapper(*some):
Исправлено

2021-11-30 11:31 UTC, zhuchkov-artem commented on homework2/hw5.py
> +    for i, element in enumerate(data):
Исправлено

2021-11-30 11:32 UTC, zhuchkov-artem commented on homework2/hw5.py
> +        if element == stop:
Исправлено

2021-11-30 11:32 UTC, zhuchkov-artem commented on tests/homework2/test_hw2.py
> +def test_1_major_and_minor_elem():
Исправлено

2021-12-02 08:07 UTC, zhuchkov-artem commented on homework2/hw1.py
> +                if ord(char) > 127:
Исправлено

2021-12-02 08:08 UTC, zhuchkov-artem commented on homework2/hw1.py
> +    chars_stat = Counter()
Исправлено

2021-12-02 08:08 UTC, zhuchkov-artem commented on homework2/hw1.py
> +                if char in string.punctuation:
Исправлено

2021-12-07 19:06 UTC, PeppaTheC approved these changes

2021-12-09 13:06 UTC, merged