Homework # 03 completed
zhuchkov-artem/homework-repository pull request #3
Opened 2021-11-16 19:21 UTC by zhuchkov-artem

2021-11-21 17:40 UTC, PeppaTheC requested changes

2021-11-21 17:40 UTC, PeppaTheC commented on homework3/task01.py
> +        def wrapper(*some):
some? что такое название переменной значит?
согласно такому способу можно кэшировать только функцию без default args и kwargs

2021-11-21 17:40 UTC, PeppaTheC commented on homework3/task02.py
> +    with Pool(processes=50) as pool:
50 - магическое число, откуда оно взялось?

2021-11-21 17:40 UTC, PeppaTheC commented on homework3/task03.py
> +# positive_even = Filter([lambda a: a % 2 == 0,
я думаю автор хотел оставить распаковку и запаковку.

2021-12-02 12:46 UTC, zhuchkov-artem commented on homework3/task01.py
> +        def wrapper(*some):
Исправлено

2021-12-05 17:24 UTC, zhuchkov-artem commented on homework3/task02.py
> +    with Pool(processes=50) as pool:
multiprocessing.cpu_count() мне выдало 4. Но в данной задаче количество процессов может же превышать количество ядер потому что основное время выполнения функции - это sleep. В связи с этим я указал побольше процессов, чтобы итоговое время уложилось в 60 сек. В данном случае ограничение по количеству процессов у меня было 61 - если ставить больше, то вылетает исключение.

2021-12-05 17:42 UTC, zhuchkov-artem commented on homework3/task03.py
> +# positive_even = Filter([lambda a: a % 2 == 0,
Не совсем понял где я убрал запаковку и распаковку.

2021-12-07 19:08 UTC, PeppaTheC approved these changes

2021-12-07 19:08 UTC, PeppaTheC commented on homework3/task01.py
> +        def wrapper(*args, **kwargs):
спасение от default аргументов в модуле inspect

2021-12-07 19:09 UTC, PeppaTheC commented on homework3/task03.py
> +# positive_even = Filter([lambda a: a % 2 == 0,
Filter(lambda a: a % 2 == 0, lambda a: a % 3 == 0) - типо так

2021-12-09 13:30 UTC, merged