Homework # 4 completed
zhuchkov-artem/homework-repository pull request #4
Opened 2021-11-22 21:09 UTC by zhuchkov-artem

2021-11-29 13:05 UTC, PeppaTheC requested changes

2021-11-29 13:05 UTC, PeppaTheC commented on homework4/task_1_read_file.py
> +    except Exception as exp:
Exception - очень плохо так перехватывать. Нужно конкретно указывать, что мы хотим перехватить и обрабатывать конкретный exception.

2021-11-29 13:05 UTC, PeppaTheC commented on homework4/task_1_read_file.py
> +    except Exception as exp:
тут может быть и кодировка файла, и файла может не существовать и т.п.

2021-11-29 13:05 UTC, PeppaTheC commented on homework4/task_2_mock_input.py
> +    except Exception:
тоже самое. http ошибки здесь надо ловить.

2021-11-29 13:05 UTC, PeppaTheC commented on tests/homework4/test_task_1.py
> +    with open(file='test_file.txt', mode='w', encoding='utf8') as file:
лучше использовать temfile из стандартной библиотеке python

2021-11-29 13:05 UTC, PeppaTheC commented on tests/homework4/test_task_1.py
> +def create_and_del_true_file():
фикстуры обычно не обозначают действия. А какую то структуру данных.
тут это просто 
def file_with_1_in_first_line ...

2021-11-29 13:05 UTC, PeppaTheC commented on tests/homework4/test_task_2.py
> +    with patch(target=path_for_mock, return_value='iii'):
при смене путей, потом будет тяжело следить куда этот путь вел, почему просто не `patch.object(get_html_from_url)`

2021-12-05 09:07 UTC, zhuchkov-artem commented on homework4/task_1_read_file.py
> +    except Exception as exp:
В задании указано, что в случае любой ошибки выбрасывать ValueError

2021-12-05 14:05 UTC, zhuchkov-artem commented on tests/homework4/test_task_1.py
> +def create_and_del_true_file():
Исправлено

2021-12-05 14:58 UTC, zhuchkov-artem commented on homework4/task_2_mock_input.py
> +    except Exception:
Чтобы отлавливать http ошибки - их надо импортировать из библиотеки и затем отлавливать?

2021-12-05 14:59 UTC, zhuchkov-artem commented on tests/homework4/test_task_1.py
> +    with open(file='test_file.txt', mode='w', encoding='utf8') as file:
По tempfile задал вопрос в Teams.

2021-12-05 16:03 UTC, zhuchkov-artem commented on tests/homework4/test_task_2.py
> +    with patch(target=path_for_mock, return_value='iii'):
Из документации :
You can either call patch.object() with three arguments or two arguments. The three argument form takes the object to be patched, the attribute name and the object to replace the attribute with.
В прошлой реализации этого задания get_html_from_url была функцией и ее надо было заменить на что-то другое. Но согласно документации надо указать как минимум 2 параметра: <объект для патча> и <атрибут этого объекта>. А если мне надо переопределить не какой-то один атрибут, а в целом функцию или класс (в текущей реализации это задание выполнено с помощью класса) - как в таком случае воспользоваться patch.object?

2021-12-07 19:11 UTC, PeppaTheC commented on homework4/task_2_mock_input.py
> +    except Exception:
да

2021-12-07 19:18 UTC, PeppaTheC commented on tests/homework4/test_task_2.py
> +    with patch(target=path_for_mock, return_value='iii'):
- тут дело больше в удобстве, объекты ты можешь смотреть и отслеживать легко в pycharm. при переносе кода или переименовании. Pycharm за тебя переименует эти объекты везде и поправит пути импорта. 
- через указания полного пути через строку, это надо будет делать вручную, просто сложнее. 

по поводу объектов, все в питоне объект 
```
import module_name
with patch.object(module_name, 'function_name', return_value='iii'): 
```

Но это так минорный комент,

2021-12-07 19:19 UTC, PeppaTheC approved these changes

2021-12-09 17:09 UTC, merged