Homework # 5 completed
zhuchkov-artem/homework-repository pull request #5
Opened 2021-11-30 14:30 UTC by zhuchkov-artem

2021-12-07 19:25 UTC, PeppaTheC requested changes

2021-12-07 19:25 UTC, PeppaTheC commented on homework5/save_original_info.py
> +    wrapper = CustomWraps(func, wrapper)
``Написать декоратор```
тут явно имелось ввиду, что можно декарировать через @

2021-12-07 19:25 UTC, PeppaTheC commented on tests/homework5/test_oop_1.py
> +teacher = Teacher('Daniil', 'Shadrin')
тут таких тестов нет, 
но все же я бы эти данные оформил в виде фикстур, так как тесты могут быть разными и они предполагают, что одни тесты могу менять атрибуты или удалять интсансы вовсе. Хотелось бы иметь fucntion scope fixtures

2021-12-10 12:29 UTC, zhuchkov-artem commented on homework5/save_original_info.py
> +    wrapper = CustomWraps(func, wrapper)
Исправлено

2021-12-10 18:48 UTC, zhuchkov-artem commented on tests/homework5/test_oop_1.py
> +teacher = Teacher('Daniil', 'Shadrin')
Исправил

2021-12-13 11:21 UTC, PeppaTheC approved these changes

2021-12-13 11:45 UTC, merged