Homework # 6 completed
zhuchkov-artem/homework-repository pull request #6
Opened 2021-12-06 16:08 UTC by zhuchkov-artem

2021-12-07 19:30 UTC, PeppaTheC requested changes

2021-12-07 19:30 UTC, PeppaTheC commented on homework6/oop_2.py
> +    @staticmethod
почему это staticmethod, а не classmethod
если я отнаследуюсь например  ProTeacher, я бы хотел складывать в словарь уже нового класса при вызове check_homework

2021-12-07 19:30 UTC, PeppaTheC commented on homework6/oop_2.py
> +    @staticmethod
то же самое про static

2021-12-07 19:30 UTC, PeppaTheC commented on tests/homework6/test_oop_2.py
> +opp_teacher = Teacher('Daniil', 'Shadrin')
почему бы не положить в фикстуры?

2021-12-25 13:43 UTC, zhuchkov-artem commented on homework6/oop_2.py
> +    @staticmethod
Исправлено

2021-12-25 13:43 UTC, zhuchkov-artem commented on homework6/oop_2.py
> +    @staticmethod
Исправлено

2021-12-25 13:43 UTC, zhuchkov-artem commented on tests/homework6/test_oop_2.py
> +opp_teacher = Teacher('Daniil', 'Shadrin')
Исправлено

2021-12-26 21:28 UTC, PeppaTheC approved these changes

2021-12-28 10:02 UTC, merged