Homework # 9 completed
zhuchkov-artem/homework-repository pull request #9
Opened 2021-12-19 14:03 UTC by zhuchkov-artem

2021-12-20 16:31 UTC, PeppaTheC requested changes

2021-12-20 16:31 UTC, PeppaTheC commented on homework9/hw1.py
> +def merge_sorted_files(file_list: List[Union[Path, str]]) -> Iterator:
probably expected output too be sorted too

2021-12-25 09:43 UTC, zhuchkov-artem commented on homework9/hw1.py
> +def merge_sorted_files(file_list: List[Union[Path, str]]) -> Iterator:
Исправлено

2021-12-26 21:27 UTC, PeppaTheC approved these changes

2021-12-28 10:01 UTC, merged